server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: q123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
